### ISSUE TITLE
A test question about visual grounding

### ISSUE THREAD

**Issue by romanticegg** [OFA-Sys/ONE-PEACE#29]
Hello, I am testing the function of visual grounding, when the prompt is the thing really in the picture, it seems like ok, but when I change the promt to 'person'(there are more than one person in the picture), it can just return one detection box, when I change the prompt to the thing not in the picture, it still return a box. I want to know it there anything wrong with my test method?(I use the API sample), thanks a lot.

**Comment by logicwong** [comment]
@romanticegg Hello, currently the Visual Grounding API is finetuned on the RefCOCOg dataset. Each prompt in this dataset corresponds to only one object in the image, and it does not consider the case where the object does not in the picture, which is why you are experiencing the mentioned issue.
If you want to return multiple results or want the model to return nothing if the object is not in the picture, you need to finetune it on your own dataset.
